---
.travis.yml:
  branches:
    - main
    - master
spec/spec_helper.rb:
  mock_with: ':rspec'
  strict_level: ':error'
Rakefile:
  extras:
    - |
      Blacksmith::RakeTask.new do |t|
        t.commit_message_pattern = "Bump version to %s"
        t.tag_message_pattern = "Release %s"
        t.tag_pattern = "%s"
        t.tag_sign = true
      end
Gemfile:
  required:
    ':system_tests':
      - gem: ed25519
        version: '~> 1.2'
      - gem: bcrypt_pbkdf
        version: '~> 1.0'
