#!/bin/sh
#
# This file is managed by Puppet, and is part of the ssm/nifi_toolkit
# puppet module. Local modifications will be lost.
#
set -u

if [ -z "${JAVA_HOME:-}" ]; then
    JAVA_HOME=$(readlink -f $(which java) | sed -e 's,/bin/java$,,')
    export JAVA_HOME
fi
exec /opt/nifi-toolkit/current/bin/cli.sh "$@"
